In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\amren\Downloads\sales_raw_ Sheet1.csv")

In [5]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001  1/13/2023    Rohit  South   Mobile  23289  19118
1      1002  10/7/2023     Aman   West   Laptop   8905   5593
2      1003  11/5/2023    Rahul  South  Monitor  59987  39959
3      1004  2/19/2024    Rahul  South  Printer  49597  33892
4      1005  1/26/2024   Anjali  North   Laptop  54797  34468

In [7]:
df.shape

(520, 7)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    object
 2   Customer    520 non-null    object
 3   Region      520 non-null    object
 4   Product     520 non-null    object
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: int64(3), object(4)
memory usage: 28.6+ KB

In [11]:
df = df.drop_duplicates()

In [13]:
df.shape

(500, 7)

In [19]:
#fix date column
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors= 'coerce')

In [21]:
df = df.dropna(subset=['Order_Date'])

In [23]:
df.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

In [25]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [27]:
df ['Profit'] = df[ 'Sales']-df['Cost']

df['Year'] = df ['Order_Date'].dt.year 

df['Month'] = df[ 'Order_Date'].dt.month

In [29]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [33]:
df.to_csv('Sales_Cleaned.csv' , index = 'false')

In [9]:
import pandas as pd
from sqlalchemy import create_engine
df = pd.read_csv(r"D:\analysts prj\Sales_Cleaned.csv")


# MySQL connection
username = "root"
password = "Karan748482"
host = "localhost"
port = "3306"
database = "sales_analytics"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "orders"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM orders LIMIT 5;", engine)

,Unnamed: 0,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1